version: '3.7'

services:
  chat:
    container_name: wserver
    build:
      context: ./backend
    ports:
      - 5000:5000
    volumes:
      - ./backend:/usr/app
    networks:
      - chat
  client:
    container_name: client
    build:
      context: ./client
    environment:
      - REACT_APP_SOCKET=ws://chat:5000/ws
    ports:
      - 3000:3000
    depends_on:
      - chat
    volumes:
      - ./client:/usr/app
      - /usr/app/node_modules
    networks:
      - chat
networks:
  chat:
    driver: bridge
